ecomerce/ecomerce/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ecomerce.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'productos.views.home', name='home'),
    url(r'^productos/$', 'productos.views.todos', name='productos'),

    url(r'^admin/', include(admin.site.urls)),
)

ecomerce/productos/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    Titulo = models.CharField(max_length=120)
    Descripcion = models.TextField(null=True, blank=True)
    Precio = models.DecimalField(decimal_places=2, max_digits=100, default= 29.99)
    Precio_Ventas = models.DecimalField(decimal_places=2, max_digits=100, null= True, blank= True)
    slug = models.SlugField()
    timestamp = models.DateTimeField(auto_now_add = True, auto_now= False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.Titulo
    
    def get_price(self):
        return self.Precio

class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto)
    imagen = models.ImageField(upload_to='productos/imagenes/')
    featured = models.BooleanField(default = False)
    thumbail = models.BooleanField(default = False)
    updated = models.DateTimeField(auto_now_add= False, auto_now= True)
    active = models.BooleanField(default=True)
    updated= models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.producto.Titulo

ecomerce/productos/views.py
from django.shortcuts import render

# Create your views here.
from .models import Producto
def home(request):
    productos = Producto.objects.all()
    context ={'productos': productos}
    template = 'productos/home.html'
    

    return render (request, template, context)

def todos(request):
    productos = Producto.objects.all()
    context = {'productos': productos}
    template = 'productos/all.html'
    return render(request, template, context)

        

ecomerce/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{% block titulo %}{% endblock %}ONLINE STORE</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">

  </head>

  <body>

      {% include 'navbar.html' %}

    <!-- Begin page content -->
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
  </body>
</html>

ecomerce/templates/navbar.html
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">ONLINE STORE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Bienvenido <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>

ecomerce/templates/productos/all.html
{% extends 'base.html'%}

{% block content %}
<ul>
{% for productos in productos %}
<li> {{productos.Titulo}} {{productos.Precio}}</li>
{% endfor %}
</ul>>
{% endblock %}

ecomerce/templates/productos/home.html
{% extends "base.html" %}
{% block titulo %}Bienvenido {% endblock %}
 {% block content %}

<div class='row'>
{% for productos in productos %}
<div class = 'col-sm-4'>
{% for item in productos.productoimagen_set.all %}
{% if item.featured %}
<img src="{{ MEDIA_URL }}{{ item.imagen }}"/>
{% endif %}

{% endfor %}
{{productos.id}}
{{productos.Titulo}}
{{productos.Precio}}
</div>
{% endfor %}
{% endblock %}